//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElemnetUi_Vue.JS_Mvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ElementVueMvcEntities : DbContext
    {
        public ElementVueMvcEntities()
            : base("name=ElementVueMvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_sysUser> t_sysUser { get; set; }
    
        public virtual int ProcEditUserPwd(string userName, string userPwdOld, string userPwdNew, ObjectParameter returnMsg)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var userPwdOldParameter = userPwdOld != null ?
                new ObjectParameter("userPwdOld", userPwdOld) :
                new ObjectParameter("userPwdOld", typeof(string));
    
            var userPwdNewParameter = userPwdNew != null ?
                new ObjectParameter("userPwdNew", userPwdNew) :
                new ObjectParameter("userPwdNew", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcEditUserPwd", userNameParameter, userPwdOldParameter, userPwdNewParameter, returnMsg);
        }
    
        public virtual int procLogin(string userName, string userPwd, ObjectParameter returnMsg)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var userPwdParameter = userPwd != null ?
                new ObjectParameter("userPwd", userPwd) :
                new ObjectParameter("userPwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("procLogin", userNameParameter, userPwdParameter, returnMsg);
        }
    }
}
